# Generated by Django 5.0.7 on 2024-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sum', models.PositiveIntegerField(verbose_name='Cумма платежа')),
                ('payment_method', models.CharField(choices=[('cash', 'наличные'), ('transfer', 'перевод')], max_length=50, verbose_name='Способ оплаты')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id сессии')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Cсылка на оплату')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/avatars/default_avatar.jpg', null=True, upload_to='media/users/avatars', verbose_name='Аватар'),
        ),
    ]
