# Generated by Django 5.0.7 on 2024-08-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/avatars/default_avatar.jpg', null=True, upload_to='media/users/avatars', verbose_name='Аватар'),
        ),
    ]
